### PR TITLE
Update Template

### LINKED ISSUE #1: Enhancement: Update repository
### Summary

1. We want Ruff
2. We want sphinx
3. We want to use our custom starlite sphinx theme
4. Remove meta files in favor of community health files

### Basic Example

_No response_

### Drawbacks and Impact

_No response_

### Unresolved questions

_No response_

### PR DESCRIPTION
**Pull request by JacobCoffee**
### Pull Request Checklist

[//]: # "Please review the [Starlite contribution guidelines](https://github.com/starlite-api/starlite/blob/main/CONTRIBUTING.rst) for this repository."

- [x] New code has 100% test coverage
- [x] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [x] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR

By submitting this issue, you agree to: 
- follow Starlite's [Code of Conduct](https://github.com/starlite-api/.github/blob/main/CODE_OF_CONDUCT.md)
- follow Starlite's [Contribution Guidelines](https://starliteproject.dev/community/contribution-guide)

### Description

[//]: # "Please describe your pull request for new release changelog purposes"

- Migrate to ruff in CI
- Remove mkdocs in favor of sphinx
- Create a templatable landing page for starlite sphinx theme
- Update pre-commit
- Add makefile
- Remove SECURITY.md in favor of .github community health files
- Remove CODE_OF_CONDUCT.md in favor of .github community health files

### Close Issue(s)

[//]: # "Please add in issue numbers this pull request will close, if applicable"
[//]: # "Examples: Fixes #4321 or Closes #1234"
Closes #1

### CODE REVIEW

**Comment by JacobCoffee** [comment]
- [x] [Update Docker](https://github.com/starlite-api/project-template/tree/template_updates/.docker) .docker/Dockerfile

**Comment by provinzkraut** [comment]
> * [ ]  [Update Docker](https://github.com/starlite-api/project-template/tree/template_updates/.docker) .docker/Dockerfile

That file can go

**Comment by provinzkraut** [comment]
I don't think the landing page belongs here. Let's finish up the template for that and then move it to our theme.

**Comment by peterschutt** [comment]
superseded by #3

**Pull request closed without merging**
